
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Record_Retrieve.java
 *
 * Created on 13 Nov, 2011, 11:09:03 PM
 */
/**
 *
 * @author avp
 */
public class Record_Retrieve extends javax.swing.JFrame {

    /** Creates new form Record_Retrieve */
    public Record_Retrieve() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submit_eid = new javax.swing.JButton();
        submit_rno = new javax.swing.JButton();
        submit_rid = new javax.swing.JButton();
        submit_pid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Record ID");

        jLabel2.setText("Patient ID");

        jLabel3.setText("Employee ID");

        jLabel4.setText("Room No.");

        submit_eid.setText("Submit");
        submit_eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_eidActionPerformed(evt);
            }
        });

        submit_rno.setText("Submit");
        submit_rno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_rnoActionPerformed(evt);
            }
        });

        submit_rid.setText("Submit");
        submit_rid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_ridActionPerformed(evt);
            }
        });

        submit_pid.setText("Submit");
        submit_pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_pidActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Record No", "Patient ID", "Employee ID", "Room No.", "Bill Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        clear.setText("Clear All");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submit_rid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submit_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit_rno)
                    .addComponent(submit_eid))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit_eid)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit_rno)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submit_pid)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit_rid))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clear)
                        .addGap(34, 34, 34)
                        .addComponent(close)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        for (int n=0; n<20; n++)
        {
                table.setValueAt("", n, 0);
                table.setValueAt("", n, 1);
                table.setValueAt("", n, 2);
                table.setValueAt("", n, 3);
                table.setValueAt("", n, 4);
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void submit_ridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_ridActionPerformed
            int n =0, rid = Integer.parseInt(jTextField1.getText());
            ResultSet rs = null;
        try {
            JDBC pr = new JDBC();
            rs = pr.Retrieve_Record_rid(rid);
            while (rs.next())
            {
                table.setValueAt(rs.getString(1), n, 0);
                table.setValueAt(rs.getString(2), n, 1);
                table.setValueAt(rs.getString(3), n, 2);
                table.setValueAt(rs.getString(4), n, 3);
                table.setValueAt(rs.getString(5), n, 4);
                n++;
            }
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
        }
            catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Exception : " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit_ridActionPerformed

    private void submit_pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_pidActionPerformed
            int n =0, pid = Integer.parseInt(jTextField2.getText());
            ResultSet rs = null;
        try {
            JDBC pr = new JDBC();
            rs = pr.Retrieve_Record_pid(pid);
            while (rs.next())
            {
                table.setValueAt(rs.getString(1), n, 0);
                table.setValueAt(rs.getString(2), n, 1);
                table.setValueAt(rs.getString(3), n, 2);
                table.setValueAt(rs.getString(4), n, 3);
                table.setValueAt(rs.getString(5), n, 4);
                n++;
            }
            jTextField1.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }
            catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Exception : " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit_pidActionPerformed

    private void submit_eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_eidActionPerformed
            int n =0, eid = Integer.parseInt(jTextField3.getText());
            ResultSet rs = null;
        try {
            JDBC pr = new JDBC();
            rs = pr.Retrieve_Record_eid(eid);
            while (rs.next())
            {
                table.setValueAt(rs.getString(1), n, 0);
                table.setValueAt(rs.getString(2), n, 1);
                table.setValueAt(rs.getString(3), n, 2);
                table.setValueAt(rs.getString(4), n, 3);
                table.setValueAt(rs.getString(5), n, 4);
                n++;
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
        }
            catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Exception : " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit_eidActionPerformed

    private void submit_rnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_rnoActionPerformed
            int n =0, rno = Integer.parseInt(jTextField4.getText());
            ResultSet rs = null;
        try {
            JDBC pr = new JDBC();
            rs = pr.Retrieve_Record_rno(rno);
            while (rs.next())
            {
                table.setValueAt(rs.getString(1), n, 0);
                table.setValueAt(rs.getString(2), n, 1);
                table.setValueAt(rs.getString(3), n, 2);
                table.setValueAt(rs.getString(4), n, 3);
                table.setValueAt(rs.getString(5), n, 4);
                n++;
            }
            jTextField3.setText("");
            jTextField2.setText("");
            jTextField1.setText("");
        }
            catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Exception : " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_rnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void NewMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Record_Retrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Record_Retrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Record_Retrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Record_Retrieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Record_Retrieve().setVisible(true);
            }
           
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton submit_eid;
    private javax.swing.JButton submit_pid;
    private javax.swing.JButton submit_rid;
    private javax.swing.JButton submit_rno;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
